language: node_js
node_js: "node"

jobs:
  include:
    - name: Run client tests
      install:
        - cd client
        - npm install
      script: 
        - npm test
    - name: Run server tests
      install:
        - cd server
        - npm install
      script:
        - npm test
    - name: Build client tests
      install:
        - cd client
        - npm install
      script:
        - npm test
    - name: Build server tests
      install:
        - cd server
        - npm install
      script:
        - npm test
        
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt